# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
dependencies:
    - OpenZeppelin/openzeppelin-contracts@3.4.0
reports:
  exclude_contracts:
    - SafeMath
compiler:
    evm_version: null
    solc:
        version: 0.7.5
        optimizer:
            enabled: true
            runs: 200
    vyper:
        version: null
networks:
    development:
        # gas_limit: max
        # gas_buffer: 1
        # gas_price: 0
        # reverting_tx_gas_limit: max
        # default_contract_owner: true
        cmd_settings:
            # port: 8545
            # gas_limit: 6721975
            # accounts: 10
            # chain_id: 1337
            # network_id: 1588949648
            # evm_version: istanbul
            # fork: null
            # mnemonic: brownie
            # block_time: 0
            default_balance: 10000
            # time: 2020-05-08T14:54:08+0000
            # unlock: null